"""
======================================================================
YOLO TRAFFIC LSTM BASELINE COMPARISON
======================================================================

Purpose:
    Compare the trained YOLO Traffic LSTM model against a simple
    persistence / naive forecasting baseline.

Baseline assumption:
    The next traffic state is equal to the latest observed state.

    baseline_prediction(t+1) = X_test(t, last timestep)

Pipeline:
    1. Load training configuration
    2. Load test dataset
    3. Load feature metadata
    4. Load target scaler
    5. Load LSTM predictions generated by evaluation
    6. Generate persistence baseline predictions
    7. Validate predictions
    8. Calculate scaled metrics
    9. Inverse transform to original traffic scale
    10. Calculate original-scale metrics
    11. Compare LSTM vs Persistence
    12. Evaluate per traffic feature
    13. Evaluate per sensor
    14. Calculate improvement percentage
    15. Save comparison CSV
    16. Save baseline predictions
    17. Generate comparison plots
    18. Save baseline comparison report

Expected directory:

    outputs/
    └── yolo/
        ├── processed/
        │   ├── X_test.npy
        │   ├── y_test.npy
        │   ├── scaler_X.pkl
        │   ├── scaler_y.pkl              (preferred)
        │   ├── feature_metadata.json
        │   └── sensor_config.json
        │
        ├── models/
        │   └── training_config.json
        │
        └── evaluation/
            ├── y_test_prediction_original.npy
            ├── y_test_actual_original.npy
            └── ...
"""

from pathlib import Path
import json
import pickle
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
)

warnings.filterwarnings("ignore")


# ======================================================================
# PATH CONFIGURATION
# ======================================================================

SCRIPT_DIR = Path(__file__).resolve().parent

FORECASTING_DIR = SCRIPT_DIR.parent.parent

OUTPUT_DIR = (
    FORECASTING_DIR
    / "outputs"
    / "yolo"
)

PROCESSED_DIR = (
    OUTPUT_DIR
    / "processed"
)

MODEL_DIR = (
    OUTPUT_DIR
    / "models"
)

EVALUATION_DIR = (
    OUTPUT_DIR
    / "evaluation"
)

BASELINE_DIR = (
    EVALUATION_DIR
    / "baseline"
)

PLOT_DIR = (
    BASELINE_DIR
    / "plots"
)

BASELINE_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

PLOT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ======================================================================
# FILE PATHS
# ======================================================================

X_TEST_PATH = (
    PROCESSED_DIR
    / "X_test.npy"
)

Y_TEST_PATH = (
    PROCESSED_DIR
    / "y_test.npy"
)

SCALER_Y_PATH = (
    PROCESSED_DIR
    / "scaler_y.pkl"
)

SCALER_X_PATH = (
    PROCESSED_DIR
    / "scaler_X.pkl"
)

FEATURE_METADATA_PATH = (
    PROCESSED_DIR
    / "feature_metadata.json"
)

SENSOR_CONFIG_PATH = (
    PROCESSED_DIR
    / "sensor_config.json"
)

CONFIG_PATH = (
    MODEL_DIR
    / "training_config.json"
)

LSTM_PREDICTION_PATH = (
    EVALUATION_DIR
    / "y_test_prediction_original.npy"
)

ACTUAL_ORIGINAL_PATH = (
    EVALUATION_DIR
    / "y_test_actual_original.npy"
)


# ======================================================================
# DEFAULT CONFIGURATION
# ======================================================================

APPROACHES = [
    "north",
    "east",
    "south",
    "west",
]

LANES = [
    "lane_1",
    "lane_2",
    "lane_3",
]

FEATURES = [
    "vehicle_count",
    "car_count",
    "motorcycle_count",
    "bus_count",
    "truck_count",
    "queue_length_veh",
    "queue_length_m_est",
    "density_index",
]

NUM_SENSORS = 12
NUM_FEATURES = 8


# ======================================================================
# UTILITY
# ======================================================================

def print_header(title):

    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


def print_subheader(title):

    print()
    print("-" * 70)
    print(title)
    print("-" * 70)


def ensure_file(
    path,
    description,
):

    if not path.exists():

        raise FileNotFoundError(
            f"\n[ERROR] {description} tidak ditemukan:\n"
            f"        {path}\n"
        )


def save_json(
    data,
    path,
):

    with open(
        path,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            data,
            f,
            indent=4,
            ensure_ascii=False,
            default=str,
        )


# ======================================================================
# LOAD CONFIG
# ======================================================================

def load_training_config():

    print_header(
        "LOADING TRAINING CONFIGURATION"
    )

    ensure_file(
        CONFIG_PATH,
        "Training configuration",
    )

    with open(
        CONFIG_PATH,
        "r",
        encoding="utf-8",
    ) as f:

        config = json.load(f)

    print(
        f"[INFO] Dataset          : "
        f"{config.get('dataset', 'N/A')}"
    )

    print(
        f"[INFO] Model            : "
        f"{config.get('model', 'N/A')}"
    )

    print(
        f"[INFO] Input size       : "
        f"{config.get('input_size', 'N/A')}"
    )

    print(
        f"[INFO] Output size      : "
        f"{config.get('output_size', 'N/A')}"
    )

    print(
        f"[INFO] Sequence length  : "
        f"{config.get('sequence_length', 'N/A')}"
    )

    print(
        f"[INFO] Forecast horizon : "
        f"{config.get('forecast_horizon', 'N/A')} second"
    )

    print(
        "[OK] Training configuration loaded."
    )

    return config


# ======================================================================
# LOAD DATA
# ======================================================================

def load_test_data():

    print_header(
        "LOADING TEST DATA"
    )

    ensure_file(
        X_TEST_PATH,
        "X_test.npy",
    )

    ensure_file(
        Y_TEST_PATH,
        "y_test.npy",
    )

    X_test = np.load(
        X_TEST_PATH
    )

    y_test = np.load(
        Y_TEST_PATH
    )

    print(
        f"[INFO] X_test : "
        f"{X_test.shape}"
    )

    print(
        f"[INFO] y_test : "
        f"{y_test.shape}"
    )

    return (
        X_test,
        y_test,
    )


# ======================================================================
# LOAD FEATURE METADATA
# ======================================================================

def load_feature_metadata():

    print_header(
        "LOADING FEATURE METADATA"
    )

    ensure_file(
        FEATURE_METADATA_PATH,
        "Feature metadata",
    )

    with open(
        FEATURE_METADATA_PATH,
        "r",
        encoding="utf-8",
    ) as f:

        metadata = json.load(f)

    if "features" not in metadata:

        raise ValueError(
            "feature_metadata.json tidak memiliki "
            "key 'features'."
        )

    features = metadata["features"]

    if not isinstance(
        features,
        list,
    ):

        raise ValueError(
            "metadata['features'] harus berupa list."
        )

    if len(features) != 96:

        raise ValueError(
            f"Jumlah feature metadata salah. "
            f"Ditemukan {len(features)}, "
            f"diharapkan 96."
        )

    for i, item in enumerate(features):

        if not isinstance(
            item,
            dict,
        ):

            raise ValueError(
                f"Metadata index {i} "
                f"bukan dictionary."
            )

        required_keys = [
            "index",
            "sensor_id",
            "approach",
            "lane_id",
            "feature",
        ]

        for key in required_keys:

            if key not in item:

                raise ValueError(
                    f"Metadata index {i} "
                    f"tidak memiliki '{key}'."
                )

        if item["index"] != i:

            raise ValueError(
                f"Index metadata tidak sesuai. "
                f"Expected {i}, "
                f"got {item['index']}."
            )

    sensor_ids = sorted(
        list(
            set(
                item["sensor_id"]
                for item in features
            )
        )
    )

    print(
        f"[INFO] Feature count : "
        f"{len(features)}"
    )

    print(
        f"[INFO] Sensor count  : "
        f"{len(sensor_ids)}"
    )

    print(
        f"[INFO] Sensor IDs    : "
        f"{sensor_ids}"
    )

    print(
        "[OK] Feature metadata validation passed."
    )

    return features


# ======================================================================
# LOAD SCALER
# ======================================================================

def load_target_scaler():

    print_header(
        "LOADING TARGET SCALER"
    )

    # --------------------------------------------------------------
    # Preferred: scaler_y.pkl
    # --------------------------------------------------------------

    if SCALER_Y_PATH.exists():

        scaler_path = SCALER_Y_PATH

        print(
            "[INFO] Using scaler_y.pkl"
        )

    # --------------------------------------------------------------
    # Fallback: scaler_X.pkl
    # --------------------------------------------------------------

    elif SCALER_X_PATH.exists():

        scaler_path = SCALER_X_PATH

        print(
            "[WARN] scaler_y.pkl tidak ditemukan."
        )

        print(
            "[WARN] Menggunakan scaler_X.pkl "
            "sebagai fallback."
        )

        print(
            "[WARN] Pastikan preprocessing "
            "memang menggunakan scaler_X "
            "untuk target y."
        )

    else:

        raise FileNotFoundError(
            "Tidak ditemukan scaler_y.pkl "
            "maupun scaler_X.pkl."
        )

    with open(
        scaler_path,
        "rb",
    ) as f:

        scaler = pickle.load(f)

    print(
        f"[INFO] Scaler path : "
        f"{scaler_path}"
    )

    print(
        f"[INFO] Scaler type : "
        f"{type(scaler).__name__}"
    )

    if hasattr(
        scaler,
        "n_features_in_",
    ):

        print(
            f"[INFO] Scaler features : "
            f"{scaler.n_features_in_}"
        )

    print(
        "[OK] Target scaler loaded."
    )

    return scaler


# ======================================================================
# VALIDATE DATA
# ======================================================================

def validate_data(
    X_test,
    y_test,
    config,
):

    print_header(
        "VALIDATING TEST DATA"
    )

    # --------------------------------------------------------------
    # NaN / Inf
    # --------------------------------------------------------------

    x_nan = int(
        np.isnan(X_test).sum()
    )

    x_inf = int(
        np.isinf(X_test).sum()
    )

    y_nan = int(
        np.isnan(y_test).sum()
    )

    y_inf = int(
        np.isinf(y_test).sum()
    )

    print(
        f"[INFO] X_test | NaN: "
        f"{x_nan} | Inf: {x_inf}"
    )

    print(
        f"[INFO] y_test | NaN: "
        f"{y_nan} | Inf: {y_inf}"
    )

    if x_nan > 0 or x_inf > 0:

        raise ValueError(
            "X_test mengandung NaN atau Inf."
        )

    if y_nan > 0 or y_inf > 0:

        raise ValueError(
            "y_test mengandung NaN atau Inf."
        )

    # --------------------------------------------------------------
    # Dimensions
    # --------------------------------------------------------------

    if X_test.ndim != 3:

        raise ValueError(
            f"X_test harus 3D. "
            f"Ditemukan {X_test.ndim}D."
        )

    if y_test.ndim != 2:

        raise ValueError(
            f"y_test harus 2D. "
            f"Ditemukan {y_test.ndim}D."
        )

    expected_input_size = int(
        config["input_size"]
    )

    expected_output_size = int(
        config["output_size"]
    )

    if X_test.shape[2] != expected_input_size:

        raise ValueError(
            f"Input size mismatch.\n"
            f"Config : {expected_input_size}\n"
            f"X_test: {X_test.shape[2]}"
        )

    if y_test.shape[1] != expected_output_size:

        raise ValueError(
            f"Output size mismatch.\n"
            f"Config : {expected_output_size}\n"
            f"y_test: {y_test.shape[1]}"
        )

    if X_test.shape[0] != y_test.shape[0]:

        raise ValueError(
            "Jumlah sample X_test dan y_test "
            "tidak sama."
        )

    print(
        "[OK] Test dataset validation passed."
    )


# ======================================================================
# LOAD LSTM PREDICTIONS
# ======================================================================

def load_lstm_predictions():

    print_header(
        "LOADING LSTM PREDICTIONS"
    )

    ensure_file(
        LSTM_PREDICTION_PATH,
        "LSTM prediction result",
    )

    predictions = np.load(
        LSTM_PREDICTION_PATH
    )

    print(
        f"[INFO] LSTM prediction shape : "
        f"{predictions.shape}"
    )

    if np.isnan(predictions).any():

        raise ValueError(
            "LSTM prediction mengandung NaN."
        )

    if np.isinf(predictions).any():

        raise ValueError(
            "LSTM prediction mengandung Inf."
        )

    print(
        "[OK] LSTM predictions loaded."
    )

    return predictions


# ======================================================================
# GENERATE PERSISTENCE BASELINE
# ======================================================================

def generate_persistence_baseline(
    X_test,
):

    print_header(
        "GENERATING PERSISTENCE BASELINE"
    )

    """
    Persistence baseline:

        y_hat(t+1) = x(t)

    Karena X_test berbentuk:

        [sample, sequence_length, features]

    maka timestep terakhir:

        X_test[:, -1, :]

    digunakan sebagai prediksi untuk target berikutnya.
    """

    baseline_scaled = X_test[
        :,
        -1,
        :
    ].copy()

    print(
        f"[INFO] Baseline prediction shape : "
        f"{baseline_scaled.shape}"
    )

    if np.isnan(
        baseline_scaled
    ).any():

        raise ValueError(
            "Baseline prediction mengandung NaN."
        )

    if np.isinf(
        baseline_scaled
    ).any():

        raise ValueError(
            "Baseline prediction mengandung Inf."
        )

    print(
        "[INFO] Baseline method : Persistence"
    )

    print(
        "[INFO] Formula         : "
        "y(t+1) = y(t)"
    )

    print(
        "[OK] Persistence baseline generated."
    )

    return baseline_scaled


# ======================================================================
# METRICS
# ======================================================================

def calculate_metrics(
    y_true,
    y_pred,
):

    true_flat = y_true.reshape(
        -1
    )

    pred_flat = y_pred.reshape(
        -1
    )

    mse = mean_squared_error(
        true_flat,
        pred_flat,
    )

    rmse = np.sqrt(
        mse
    )

    mae = mean_absolute_error(
        true_flat,
        pred_flat,
    )

    return {
        "mae": float(mae),
        "rmse": float(rmse),
        "mse": float(mse),
    }


# ======================================================================
# SCALED METRICS
# ======================================================================

def evaluate_scaled(
    y_test,
    lstm_scaled,
    baseline_scaled,
):

    print_header(
        "EVALUATION - SCALED SPACE"
    )

    lstm_metrics = calculate_metrics(
        y_test,
        lstm_scaled,
    )

    baseline_metrics = calculate_metrics(
        y_test,
        baseline_scaled,
    )

    print()
    print(
        "LSTM"
    )

    print(
        f"MAE  : {lstm_metrics['mae']:.6f}"
    )

    print(
        f"RMSE : {lstm_metrics['rmse']:.6f}"
    )

    print(
        f"MSE  : {lstm_metrics['mse']:.6f}"
    )

    print()
    print(
        "PERSISTENCE"
    )

    print(
        f"MAE  : {baseline_metrics['mae']:.6f}"
    )

    print(
        f"RMSE : {baseline_metrics['rmse']:.6f}"
    )

    print(
        f"MSE  : {baseline_metrics['mse']:.6f}"
    )

    return (
        lstm_metrics,
        baseline_metrics,
    )


# ======================================================================
# INVERSE TRANSFORM
# ======================================================================

def inverse_transform(
    scaler,
    y_test,
    lstm_scaled,
    baseline_scaled,
):

    print_header(
        "INVERSE TRANSFORM"
    )

    y_true_original = scaler.inverse_transform(
        y_test
    )

    lstm_original = scaler.inverse_transform(
        lstm_scaled
    )

    baseline_original = scaler.inverse_transform(
        baseline_scaled
    )

    print(
        f"[INFO] Actual     : "
        f"{y_true_original.shape}"
    )

    print(
        f"[INFO] LSTM       : "
        f"{lstm_original.shape}"
    )

    print(
        f"[INFO] Persistence: "
        f"{baseline_original.shape}"
    )

    print(
        "[OK] Inverse transformation completed."
    )

    return (
        y_true_original,
        lstm_original,
        baseline_original,
    )


# ======================================================================
# ORIGINAL SCALE METRICS
# ======================================================================

def evaluate_original_scale(
    y_true,
    lstm_pred,
    baseline_pred,
):

    print_header(
        "EVALUATION - ORIGINAL TRAFFIC SCALE"
    )

    lstm_metrics = calculate_metrics(
        y_true,
        lstm_pred,
    )

    baseline_metrics = calculate_metrics(
        y_true,
        baseline_pred,
    )

    print()
    print(
        "LSTM"
    )

    print(
        f"MAE  : {lstm_metrics['mae']:.6f}"
    )

    print(
        f"RMSE : {lstm_metrics['rmse']:.6f}"
    )

    print(
        f"MSE  : {lstm_metrics['mse']:.6f}"
    )

    print()
    print(
        "PERSISTENCE"
    )

    print(
        f"MAE  : {baseline_metrics['mae']:.6f}"
    )

    print(
        f"RMSE : {baseline_metrics['rmse']:.6f}"
    )

    print(
        f"MSE  : {baseline_metrics['mse']:.6f}"
    )

    return (
        lstm_metrics,
        baseline_metrics,
    )


# ======================================================================
# IMPROVEMENT
# ======================================================================

def calculate_improvement(
    baseline_value,
    model_value,
):

    if baseline_value == 0:

        return None

    improvement = (
        (
            baseline_value
            - model_value
        )
        / baseline_value
    ) * 100.0

    return float(
        improvement
    )


# ======================================================================
# PER FEATURE COMPARISON
# ======================================================================

def evaluate_per_feature(
    y_true,
    lstm_pred,
    baseline_pred,
    metadata,
):

    print_header(
        "COMPARISON PER TRAFFIC FEATURE"
    )

    rows = []

    for feature in FEATURES:

        indices = [
            i
            for i, item in enumerate(
                metadata
            )
            if item["feature"] == feature
        ]

        if not indices:
            continue

        true_values = y_true[
            :,
            indices
        ]

        lstm_values = lstm_pred[
            :,
            indices
        ]

        baseline_values = baseline_pred[
            :,
            indices
        ]

        true_flat = true_values.reshape(
            -1
        )

        lstm_flat = lstm_values.reshape(
            -1
        )

        baseline_flat = baseline_values.reshape(
            -1
        )

        lstm_mae = mean_absolute_error(
            true_flat,
            lstm_flat,
        )

        lstm_mse = mean_squared_error(
            true_flat,
            lstm_flat,
        )

        lstm_rmse = np.sqrt(
            lstm_mse
        )

        baseline_mae = mean_absolute_error(
            true_flat,
            baseline_flat,
        )

        baseline_mse = mean_squared_error(
            true_flat,
            baseline_flat,
        )

        baseline_rmse = np.sqrt(
            baseline_mse
        )

        mae_improvement = calculate_improvement(
            baseline_mae,
            lstm_mae,
        )

        rmse_improvement = calculate_improvement(
            baseline_rmse,
            lstm_rmse,
        )

        rows.append(
            {
                "feature": feature,
                "lstm_mae": float(lstm_mae),
                "lstm_rmse": float(lstm_rmse),
                "lstm_mse": float(lstm_mse),
                "persistence_mae": float(
                    baseline_mae
                ),
                "persistence_rmse": float(
                    baseline_rmse
                ),
                "persistence_mse": float(
                    baseline_mse
                ),
                "mae_improvement_percent": mae_improvement,
                "rmse_improvement_percent": rmse_improvement,
                "feature_count": len(indices),
            }
        )

    df = pd.DataFrame(
        rows
    )

    print()

    print(
        df.to_string(
            index=False,
            float_format=lambda x: f"{x:.6f}",
        )
    )

    return df


# ======================================================================
# PER SENSOR COMPARISON
# ======================================================================

def evaluate_per_sensor(
    y_true,
    lstm_pred,
    baseline_pred,
    metadata,
):

    print_header(
        "COMPARISON PER SENSOR"
    )

    sensor_groups = {}

    for index, item in enumerate(
        metadata
    ):

        sensor_id = item[
            "sensor_id"
        ]

        if sensor_id not in sensor_groups:

            sensor_groups[
                sensor_id
            ] = []

        sensor_groups[
            sensor_id
        ].append(
            index
        )

    rows = []

    for sensor_id, indices in sensor_groups.items():

        true_values = y_true[
            :,
            indices
        ]

        lstm_values = lstm_pred[
            :,
            indices
        ]

        baseline_values = baseline_pred[
            :,
            indices
        ]

        true_flat = true_values.reshape(
            -1
        )

        lstm_flat = lstm_values.reshape(
            -1
        )

        baseline_flat = baseline_values.reshape(
            -1
        )

        lstm_mae = mean_absolute_error(
            true_flat,
            lstm_flat,
        )

        lstm_mse = mean_squared_error(
            true_flat,
            lstm_flat,
        )

        lstm_rmse = np.sqrt(
            lstm_mse
        )

        baseline_mae = mean_absolute_error(
            true_flat,
            baseline_flat,
        )

        baseline_mse = mean_squared_error(
            true_flat,
            baseline_flat,
        )

        baseline_rmse = np.sqrt(
            baseline_mse
        )

        mae_improvement = calculate_improvement(
            baseline_mae,
            lstm_mae,
        )

        rmse_improvement = calculate_improvement(
            baseline_rmse,
            lstm_rmse,
        )

        first_metadata = metadata[
            indices[0]
        ]

        rows.append(
            {
                "sensor_id": sensor_id,
                "approach": first_metadata[
                    "approach"
                ],
                "lane_id": first_metadata[
                    "lane_id"
                ],
                "sensor": (
                    f"{first_metadata['approach']}/"
                    f"{first_metadata['lane_id']}"
                ),
                "lstm_mae": float(
                    lstm_mae
                ),
                "lstm_rmse": float(
                    lstm_rmse
                ),
                "lstm_mse": float(
                    lstm_mse
                ),
                "persistence_mae": float(
                    baseline_mae
                ),
                "persistence_rmse": float(
                    baseline_rmse
                ),
                "persistence_mse": float(
                    baseline_mse
                ),
                "mae_improvement_percent": mae_improvement,
                "rmse_improvement_percent": rmse_improvement,
                "feature_count": len(indices),
            }
        )

    df = pd.DataFrame(
        rows
    )

    print()

    print(
        df.to_string(
            index=False,
            float_format=lambda x: f"{x:.6f}",
        )
    )

    return df


# ======================================================================
# SAVE PREDICTIONS
# ======================================================================

def save_predictions(
    y_true,
    baseline_scaled,
    baseline_original,
):

    print_header(
        "SAVING BASELINE PREDICTIONS"
    )

    np.save(
        BASELINE_DIR
        / "persistence_prediction_scaled.npy",
        baseline_scaled,
    )

    np.save(
        BASELINE_DIR
        / "persistence_prediction_original.npy",
        baseline_original,
    )

    np.save(
        BASELINE_DIR
        / "actual_original.npy",
        y_true,
    )

    print(
        "[SAVED] persistence_prediction_scaled.npy"
    )

    print(
        "[SAVED] persistence_prediction_original.npy"
    )

    print(
        "[SAVED] actual_original.npy"
    )


# ======================================================================
# SAVE COMPARISON CSV
# ======================================================================

def save_comparison_csv(
    feature_df,
    sensor_df,
):

    print_header(
        "SAVING COMPARISON TABLES"
    )

    feature_path = (
        BASELINE_DIR
        / "comparison_per_feature.csv"
    )

    sensor_path = (
        BASELINE_DIR
        / "comparison_per_sensor.csv"
    )

    feature_df.to_csv(
        feature_path,
        index=False,
    )

    sensor_df.to_csv(
        sensor_path,
        index=False,
    )

    print(
        f"[SAVED] {feature_path}"
    )

    print(
        f"[SAVED] {sensor_path}"
    )


# ======================================================================
# PLOT FEATURE COMPARISON
# ======================================================================

def plot_feature_comparison(
    feature_df,
):

    print_header(
        "PLOTTING FEATURE COMPARISON"
    )

    if feature_df.empty:
        return

    x = np.arange(
        len(feature_df)
    )

    width = 0.36

    plt.figure(
        figsize=(14, 7)
    )

    plt.bar(
        x - width / 2,
        feature_df[
            "lstm_mae"
        ],
        width,
        label="LSTM",
    )

    plt.bar(
        x + width / 2,
        feature_df[
            "persistence_mae"
        ],
        width,
        label="Persistence",
    )

    plt.xticks(
        x,
        feature_df[
            "feature"
        ],
        rotation=45,
        ha="right",
    )

    plt.xlabel(
        "Traffic Feature"
    )

    plt.ylabel(
        "MAE"
    )

    plt.title(
        "LSTM vs Persistence Baseline - MAE per Feature"
    )

    plt.legend()

    plt.grid(
        axis="y",
        alpha=0.3,
    )

    plt.tight_layout()

    output_path = (
        PLOT_DIR
        / "lstm_vs_persistence_mae_per_feature.png"
    )

    plt.savefig(
        output_path,
        dpi=200,
    )

    plt.close()

    print(
        f"[SAVED] {output_path}"
    )


# ======================================================================
# PLOT SENSOR COMPARISON
# ======================================================================

def plot_sensor_comparison(
    sensor_df,
):

    print_header(
        "PLOTTING SENSOR COMPARISON"
    )

    if sensor_df.empty:
        return

    x = np.arange(
        len(sensor_df)
    )

    width = 0.36

    plt.figure(
        figsize=(14, 7)
    )

    plt.bar(
        x - width / 2,
        sensor_df[
            "lstm_mae"
        ],
        width,
        label="LSTM",
    )

    plt.bar(
        x + width / 2,
        sensor_df[
            "persistence_mae"
        ],
        width,
        label="Persistence",
    )

    plt.xticks(
        x,
        sensor_df[
            "sensor"
        ],
        rotation=45,
        ha="right",
    )

    plt.xlabel(
        "Traffic Sensor"
    )

    plt.ylabel(
        "MAE"
    )

    plt.title(
        "LSTM vs Persistence Baseline - MAE per Sensor"
    )

    plt.legend()

    plt.grid(
        axis="y",
        alpha=0.3,
    )

    plt.tight_layout()

    output_path = (
        PLOT_DIR
        / "lstm_vs_persistence_mae_per_sensor.png"
    )

    plt.savefig(
        output_path,
        dpi=200,
    )

    plt.close()

    print(
        f"[SAVED] {output_path}"
    )


# ======================================================================
# PLOT IMPROVEMENT
# ======================================================================

def plot_improvement(
    feature_df,
):

    print_header(
        "PLOTTING LSTM IMPROVEMENT"
    )

    if feature_df.empty:
        return

    values = (
        feature_df[
            "mae_improvement_percent"
        ]
        .fillna(0)
    )

    plt.figure(
        figsize=(14, 7)
    )

    plt.bar(
        feature_df[
            "feature"
        ],
        values,
    )

    plt.axhline(
        0,
        linewidth=1,
    )

    plt.xlabel(
        "Traffic Feature"
    )

    plt.ylabel(
        "MAE Improvement (%)"
    )

    plt.title(
        "LSTM Improvement over Persistence Baseline"
    )

    plt.xticks(
        rotation=45,
        ha="right",
    )

    plt.grid(
        axis="y",
        alpha=0.3,
    )

    plt.tight_layout()

    output_path = (
        PLOT_DIR
        / "lstm_mae_improvement_per_feature.png"
    )

    plt.savefig(
        output_path,
        dpi=200,
    )

    plt.close()

    print(
        f"[SAVED] {output_path}"
    )


# ======================================================================
# SAVE FINAL REPORT
# ======================================================================

def save_final_report(
    config,
    scaled_metrics,
    original_metrics,
    feature_df,
    sensor_df,
):

    print_header(
        "SAVING BASELINE COMPARISON REPORT"
    )

    lstm_scaled = scaled_metrics[
        "lstm"
    ]

    persistence_scaled = scaled_metrics[
        "persistence"
    ]

    lstm_original = original_metrics[
        "lstm"
    ]

    persistence_original = original_metrics[
        "persistence"
    ]

    report = {

        "experiment": (
            "LSTM vs Persistence Baseline"
        ),

        "dataset": config.get(
            "dataset"
        ),

        "model": config.get(
            "model"
        ),

        "sequence_length": config.get(
            "sequence_length"
        ),

        "forecast_horizon": config.get(
            "forecast_horizon"
        ),

        "baseline": {
            "name": "Persistence",
            "definition": (
                "y(t+1) = y(t)"
            ),
        },

        "scaled_metrics": {

            "lstm": lstm_scaled,

            "persistence": persistence_scaled,

            "mae_improvement_percent": (
                calculate_improvement(
                    persistence_scaled["mae"],
                    lstm_scaled["mae"],
                )
            ),

            "rmse_improvement_percent": (
                calculate_improvement(
                    persistence_scaled["rmse"],
                    lstm_scaled["rmse"],
                )
            ),

            "mse_improvement_percent": (
                calculate_improvement(
                    persistence_scaled["mse"],
                    lstm_scaled["mse"],
                )
            ),
        },

        "original_scale_metrics": {

            "lstm": lstm_original,

            "persistence": persistence_original,

            "mae_improvement_percent": (
                calculate_improvement(
                    persistence_original["mae"],
                    lstm_original["mae"],
                )
            ),

            "rmse_improvement_percent": (
                calculate_improvement(
                    persistence_original["rmse"],
                    lstm_original["rmse"],
                )
            ),

            "mse_improvement_percent": (
                calculate_improvement(
                    persistence_original["mse"],
                    lstm_original["mse"],
                )
            ),
        },

        "feature_summary": {

            "best_lstm_improvement": (
                float(
                    feature_df[
                        "mae_improvement_percent"
                    ].max()
                )
                if not feature_df.empty
                else None
            ),

            "worst_lstm_improvement": (
                float(
                    feature_df[
                        "mae_improvement_percent"
                    ].min()
                )
                if not feature_df.empty
                else None
            ),

            "features_lstm_better": (
                int(
                    (
                        feature_df[
                            "mae_improvement_percent"
                        ]
                        > 0
                    ).sum()
                )
                if not feature_df.empty
                else 0
            ),

            "features_lstm_worse": (
                int(
                    (
                        feature_df[
                            "mae_improvement_percent"
                        ]
                        < 0
                    ).sum()
                )
                if not feature_df.empty
                else 0
            ),
        },

        "sensor_summary": {

            "best_lstm_improvement": (
                float(
                    sensor_df[
                        "mae_improvement_percent"
                    ].max()
                )
                if not sensor_df.empty
                else None
            ),

            "worst_lstm_improvement": (
                float(
                    sensor_df[
                        "mae_improvement_percent"
                    ].min()
                )
                if not sensor_df.empty
                else None
            ),

            "sensors_lstm_better": (
                int(
                    (
                        sensor_df[
                            "mae_improvement_percent"
                        ]
                        > 0
                    ).sum()
                )
                if not sensor_df.empty
                else 0
            ),

            "sensors_lstm_worse": (
                int(
                    (
                        sensor_df[
                            "mae_improvement_percent"
                        ]
                        < 0
                    ).sum()
                )
                if not sensor_df.empty
                else 0
            ),
        },

        "output_directory": str(
            BASELINE_DIR
        ),
    }

    output_path = (
        BASELINE_DIR
        / "baseline_comparison_report.json"
    )

    save_json(
        report,
        output_path,
    )

    print(
        f"[SAVED] {output_path}"
    )

    return report


# ======================================================================
# MAIN
# ======================================================================

def main():

    print()
    print("=" * 70)
    print(
        "YOLO TRAFFIC LSTM "
        "BASELINE COMPARISON"
    )
    print("=" * 70)

    print(
        f"[INFO] Output directory : "
        f"{OUTPUT_DIR}"
    )

    print(
        f"[INFO] Baseline directory : "
        f"{BASELINE_DIR}"
    )

    # --------------------------------------------------------------
    # Load configuration
    # --------------------------------------------------------------

    config = load_training_config()

    # --------------------------------------------------------------
    # Load feature metadata
    # --------------------------------------------------------------

    metadata = load_feature_metadata()

    # --------------------------------------------------------------
    # Load test data
    # --------------------------------------------------------------

    (
        X_test,
        y_test,
    ) = load_test_data()

    # --------------------------------------------------------------
    # Validate test data
    # --------------------------------------------------------------

    validate_data(
        X_test,
        y_test,
        config,
    )

    # --------------------------------------------------------------
    # Load target scaler
    # --------------------------------------------------------------

    scaler = load_target_scaler()

    # --------------------------------------------------------------
    # Load LSTM predictions
    # --------------------------------------------------------------

    lstm_original = load_lstm_predictions()

    # --------------------------------------------------------------
    # Validate LSTM prediction shape
    # --------------------------------------------------------------

    if (
        lstm_original.shape
        != y_test.shape
    ):

        raise ValueError(
            "Shape LSTM prediction "
            "tidak sama dengan y_test.\n"
            f"LSTM : {lstm_original.shape}\n"
            f"y    : {y_test.shape}"
        )

    # --------------------------------------------------------------
    # Generate persistence baseline
    # --------------------------------------------------------------

    baseline_scaled = (
        generate_persistence_baseline(
            X_test
        )
    )

    # --------------------------------------------------------------
    # Scaled LSTM prediction
    # --------------------------------------------------------------

    lstm_scaled = scaler.transform(
        lstm_original
    )

    # --------------------------------------------------------------
    # Scaled metrics
    # --------------------------------------------------------------

    (
        lstm_scaled_metrics,
        persistence_scaled_metrics,
    ) = evaluate_scaled(
        y_test=y_test,
        lstm_scaled=lstm_scaled,
        baseline_scaled=baseline_scaled,
    )

    # --------------------------------------------------------------
    # Inverse transform
    # --------------------------------------------------------------

    (
        y_true_original,
        lstm_original_from_scaler,
        baseline_original,
    ) = inverse_transform(
        scaler=scaler,
        y_test=y_test,
        lstm_scaled=lstm_scaled,
        baseline_scaled=baseline_scaled,
    )

    # --------------------------------------------------------------
    # Check LSTM original prediction consistency
    # --------------------------------------------------------------

    lstm_difference = np.max(
        np.abs(
            lstm_original
            - lstm_original_from_scaler
        )
    )

    print(
        f"[INFO] LSTM inverse-transform "
        f"consistency max error : "
        f"{lstm_difference:.10f}"
    )

    # Use the already generated original-scale
    # LSTM prediction from evaluation.
    #
    # This avoids unnecessary changes caused by
    # transforming original predictions again.

    lstm_original_final = (
        lstm_original
    )

    # --------------------------------------------------------------
    # Original-scale metrics
    # --------------------------------------------------------------

    (
        lstm_original_metrics,
        persistence_original_metrics,
    ) = evaluate_original_scale(
        y_true=y_true_original,
        lstm_pred=lstm_original_final,
        baseline_pred=baseline_original,
    )

    # --------------------------------------------------------------
    # Per feature
    # --------------------------------------------------------------

    feature_df = evaluate_per_feature(
        y_true=y_true_original,
        lstm_pred=lstm_original_final,
        baseline_pred=baseline_original,
        metadata=metadata,
    )

    # --------------------------------------------------------------
    # Per sensor
    # --------------------------------------------------------------

    sensor_df = evaluate_per_sensor(
        y_true=y_true_original,
        lstm_pred=lstm_original_final,
        baseline_pred=baseline_original,
        metadata=metadata,
    )

    # --------------------------------------------------------------
    # Save predictions
    # --------------------------------------------------------------

    save_predictions(
        y_true=y_true_original,
        baseline_scaled=baseline_scaled,
        baseline_original=baseline_original,
    )

    # --------------------------------------------------------------
    # Save comparison tables
    # --------------------------------------------------------------

    save_comparison_csv(
        feature_df,
        sensor_df,
    )

    # --------------------------------------------------------------
    # Plots
    # --------------------------------------------------------------

    plot_feature_comparison(
        feature_df
    )

    plot_sensor_comparison(
        sensor_df
    )

    plot_improvement(
        feature_df
    )

    # --------------------------------------------------------------
    # Final report
    # --------------------------------------------------------------

    scaled_metrics = {
        "lstm": lstm_scaled_metrics,
        "persistence": persistence_scaled_metrics,
    }

    original_metrics = {
        "lstm": lstm_original_metrics,
        "persistence": persistence_original_metrics,
    }

    report = save_final_report(
        config=config,
        scaled_metrics=scaled_metrics,
        original_metrics=original_metrics,
        feature_df=feature_df,
        sensor_df=sensor_df,
    )

    # --------------------------------------------------------------
    # Final summary
    # --------------------------------------------------------------

    print_header(
        "BASELINE COMPARISON SUMMARY"
    )

    print()
    print(
        "[ORIGINAL SCALE]"
    )

    print()

    print(
        "LSTM"
    )

    print(
        f"MAE  : "
        f"{lstm_original_metrics['mae']:.6f}"
    )

    print(
        f"RMSE : "
        f"{lstm_original_metrics['rmse']:.6f}"
    )

    print(
        f"MSE  : "
        f"{lstm_original_metrics['mse']:.6f}"
    )

    print()

    print(
        "PERSISTENCE"
    )

    print(
        f"MAE  : "
        f"{persistence_original_metrics['mae']:.6f}"
    )

    print(
        f"RMSE : "
        f"{persistence_original_metrics['rmse']:.6f}"
    )

    print(
        f"MSE  : "
        f"{persistence_original_metrics['mse']:.6f}"
    )

    print()

    overall_mae_improvement = (
        calculate_improvement(
            persistence_original_metrics[
                "mae"
            ],
            lstm_original_metrics[
                "mae"
            ],
        )
    )

    overall_rmse_improvement = (
        calculate_improvement(
            persistence_original_metrics[
                "rmse"
            ],
            lstm_original_metrics[
                "rmse"
            ],
        )
    )

    print(
        "[LSTM IMPROVEMENT OVER PERSISTENCE]"
    )

    print(
        f"MAE improvement  : "
        f"{overall_mae_improvement:.2f}%"
        if overall_mae_improvement is not None
        else "MAE improvement  : N/A"
    )

    print(
        f"RMSE improvement : "
        f"{overall_rmse_improvement:.2f}%"
        if overall_rmse_improvement is not None
        else "RMSE improvement : N/A"
    )

    print()

    if (
        overall_mae_improvement is not None
        and overall_mae_improvement > 0
    ):

        print(
            "[RESULT] LSTM mengungguli "
            "Persistence berdasarkan MAE."
        )

    elif (
        overall_mae_improvement is not None
        and overall_mae_improvement < 0
    ):

        print(
            "[RESULT] Persistence lebih baik "
            "daripada LSTM berdasarkan MAE."
        )

    else:

        print(
            "[RESULT] LSTM dan Persistence "
            "memiliki MAE yang sama."
        )

    print()

    print(
        "[FEATURE SUMMARY]"
    )

    print(
        f"LSTM better : "
        f"{report['feature_summary']['features_lstm_better']}"
    )

    print(
        f"LSTM worse  : "
        f"{report['feature_summary']['features_lstm_worse']}"
    )

    print()

    print(
        "[OUTPUT]"
    )

    print(
        f"{BASELINE_DIR}"
    )

    print()

    print(
        "=" * 70
    )

    print(
        "BASELINE COMPARISON COMPLETED"
    )

    print(
        "=" * 70
    )


# ======================================================================
# ENTRY POINT
# ======================================================================

if __name__ == "__main__":

    main()